### ISSUE TITLE
Error when i do Package Get

### ISSUE THREAD

**Issue by pascalf22** [fayaz07/app_intro#1]
Hello ! 

Thanks for this wonderful package... but i have an error when i do Packages Get...

IU have the lastest Flutter version.

Here my pubspec.yaml :

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  scoped_model: ^1.0.1
  http: ^0.12.0+2
  app_intro: ^1.0.2
```
And when i click to get package et have this error :

Could not un-tar (exit code 2). Error:

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\pascal.IT-PC\AppData\Local\Temp\pub_e1b64441-86f8-11e9-9c4e-d8cb8a71a093\data.tar
...... etc.....

What should i do ? Is it an error in the package ?

Thanks a lot for your reply :)

HAve a great day ! 

Pascal
